### PR TITLE
Add three books to stories page

### PR DESCRIPTION
**Pull request by davidpmccormick**
References #3415

__Needs real copy__.

image

### CODE REVIEW

**Comment by jamesgorrie** [comment]
@davidpmccormick would it be useful to sit and have a chat about how these pages might not be so static?.

**Comment by davidpmccormick** [comment]
At some point, definitely. For the time-being, the logic of which books to display where and when is still being hammered out though, so I thought getting them in statically couldn't hurt.

**Comment by jennpb** [comment]
We've now got approved copy for this! Woo!

section header =>  `Books`
body => `Get stuck into a book published by Wellcome Collection and explore the complexities of the human condition.`

**Comment by davidpmccormick** [comment]
image

**Pull request merged**
