### PR TITLE
add eventbrite widget to the bottom of the eventpage

### PR DESCRIPTION
**Pull request by jamesgorrie**
Waiting to discuss with @Heesoomoon 

eventbritewidget

### CODE REVIEW

**Comment by jamesgorrie** [comment]
@Heesoomoon @jennpb 
eventbritewidget

**Comment by jennpb** [comment]
:+1:  @jamesgorrie

**Comment by Heesoomoon** [comment]
@jennpb For CTA, here are some considerations to make 'Book tickets' more generic.
'Continue to book'
'Check dates & book'
'Check for availability'

**Comment by jamesgorrie** [comment]
> Just checking this works responsively as well?

💯 

screen shot 2018-08-13 at 18 04 57

**Pull request merged**
