### PR TITLE
Exhibition json ld

### PR DESCRIPTION
**Pull request by davidpmccormick**
References #440

## Type
🚑  Health

## Value
Adds exhibition data for SEO

## Screenshot
screen shot 2017-09-19 at 15 01 17

### All
- [x] PR labelled and assigned
- [x] Any introduced code complexity has been flagged

### CODE REVIEW

**Comment by jamesgorrie** [comment]
@davidpmccormick have you run it against:
https://search.google.com/structured-data/testing-tool ?

**Comment by jamesgorrie** [comment]
Have you noticed the errors we're getting because it's pulling schema in from the HTML?
Probably worth pulling out?

**Comment by davidpmccormick** [comment]
I have not – can you show me/explain?

**Comment by davidpmccormick** [comment]
I have now. And updated.

**Pull request merged**
