### PR TITLE
Collectors promo

### LINKED ISSUE #657: Publish Collectors standalone promo to Explore
Would like to add a standalone promo to Explore for the old style digital story, The Collectors

- [x] Promo links to http://digitalstories.wellcomecollection.org/pathways/2-the-collectors/
- [x] Summary text to be provided

IMAGES:
Original image: 
https://wellcomecloud-my.sharepoint.com/personal/t_lahdesmaki_wellcome_ac_uk/Documents/Design%20delivery/Digital%20Story%20Elements/The%20Collectors/Collectors_Plain.png

Treated PNG: 
https://wellcomecloud-my.sharepoint.com/personal/t_lahdesmaki_wellcome_ac_uk/Documents/Design%20delivery/Digital%20Story%20Elements/The%20Collectors/Collectors_Final.png

Working PSD:
https://wellcomecloud-my.sharepoint.com/personal/t_lahdesmaki_wellcome_ac_uk/Documents/Design%20delivery/Digital%20Story%20Elements/The%20Collectors/Collectors_Working.psd

### PR DESCRIPTION
**Pull request by davidpmccormick**
## What is this PR trying to achieve?
Adding a standalone promo for 'The Collectors' digital story to the explore landing page. Closes #657.

- [x] Add correct copy (replace lorem).

## What does it look like?
screen shot 2017-03-16 at 09 09 06

### CODE REVIEW

**Comment by jennpb** [comment]
@davidpmccormick can we make it turquoise?

**Comment by davidpmccormick** [comment]
> can we make it turquoise?

Yo.

**Comment by jamesgorrie** [comment]
Do we need the image in this PR if it's on Wordpress?

**Comment by davidpmccormick** [comment]
> Do we need the image in this PR if it's on Wordpress?

No, we don't – thanks; will remove.

**Pull request merged**
