### PR TITLE
add event series to Google analytics

### PR DESCRIPTION
**Pull request by jamesgorrie**
As a @hthair I'd like to use the series dimension for events as well as articles.
I'll be sure to add it to the annotations.

### CODE REVIEW

**Comment by hthair** [comment]
Will this be labelled differently? so like the above, event_series, and then article_series? Some way to filter one or the other out may be useful.

**Comment by jamesgorrie** [comment]
Nope, but you could just filter our via URL?

**Comment by hthair** [comment]
...or by showing just one 'series' like it does currently would work. e.g. go in to advanced and start typing yoga the series call that pops up and I can just view that one.

**Comment by jamesgorrie** [comment]
@hthair if it isn't good enough, we can revisit.

**Pull request merged**
