### PR TITLE
Use British 'colour' spelling for class name

### PR DESCRIPTION
**Pull request by davidpmccormick**
Fixes the result of a heavy handed find-and-replace colour -> color

### CODE REVIEW

**Comment by davidpmccormick** [comment]
I flip-flop on this – @gestchild reckons?

**Comment by gestchild** [comment]
I flip flop too. Always used colour in the past, but James makes a good point

**Comment by davidpmccormick** [comment]
OK – will use `color` everywhere (could possibly look into adding a stylelint rule that guards against using variant spellings that differ from their CSS equivalents… on a rainy day, maybe).

**Comment by jamesgorrie** [comment]
Could we close this?

**Pull request merged**
