### PR TITLE
Body squabbles from prismic

### PR DESCRIPTION
**Pull request by jamesgorrie**
## Type

✨ Feature  

## Value
Allowing us to move over to Prismic - we can start publishing Webcomics via Prismic.
This has some superfluous deduping logic, but it's useful.

Next, remove it from coming from behind a switch.

- [x] Demoed to the relevant people
- [x] PR labelled and assigned
- [x] Any introduced code complexity has been flagged

### CODE REVIEW

**Comment by jamesgorrie** [comment]
I've renamed `editorial` => `articles` to more accurately reflect what's going on in Editorial.

**Comment by jamesgorrie** [comment]
Also renamed `.content` to `.body`.
These will need to stay the same once people are using the system.

**Comment by pollecuttn** [comment]
@jamesgorrie (for when you get back from leave) - can this be closed now? Are we still waiting for anything?

**Comment by pollecuttn** [comment]
LOL - @gestchild has pointed out this is a PR not an issue!

**Pull request merged**
