### PR TITLE
Use more useful analytics dimensions

### PR DESCRIPTION
**Pull request by jamesgorrie**
## Who is this for?
👩‍🔬 

## What is it doing for them?
We're updating the dimensions to be consistent, and useful.

# Version
V1 / V2. Slowly becoming redundant, but super useful to know where the last of our V1 content is from

# Category => Format (CHANGING)
Currently has a number of things, including `public-program`, `publicprogram`, `editorial`, `collections`, `info`, `information`. Not used in reporting.

After chatting to @hthair we thought having format in here would be useful.

We have exhibition formats (perm / temp), we have event formats (discussion, workshop etc), and we've been talking about potentially using [editorial's commissioning model](https://wellcomecollection.org/pages/Wvl00yAAAB8A3y8p) to have editorial formats (Digital Story, essays, Behind-the-scenes, Galleries). 

# Series
Either event or editorial series.
Stories as a CSV with {series.title}:{series.id}

# PositionInSeries
If part of a digital story, where? (unsure if it's reported on).

# Test dimension => Test cohort (CHANGING)
Previously used to add test dimensions.
Now used for the cohort a user is in.

# Content type (CHANGING)
1 of two values, `list` or `item`.

# Referring component
Use to tell you which component led to this page view e.g. `ExhibitionPromo: index =1, Page: dateRangeName = today`

# Page state
e.g.  Page: dateRangeName = today

### CODE REVIEW

**Comment by hthair** [comment]
was 'format' an additional thing to content type or was content type also going to include article/comic/essay etc?

**Comment by jamesgorrie** [comment]
> was 'format' an additional thing to content type or was content type also going to include article/comic/essay etc?

Format was going to usurp that, but not for article, which isn't a format, but a core content type.

We need to work out a better word for content type, as content type on the site can be inferred via URL (for items) e.g. articles, events.

Does this sound like what you're expecting?

**Comment by jamesgorrie** [comment]
@hthair we could change content type to date type?

**Comment by pollecuttn** [comment]
@wellcometrust/experience-dev Can this be merged?

**Comment by jamesgorrie** [comment]
Not just yet - I'm talking to @hthair about it, but we're both busy on other things for the time being.
Are we happy for it to stay in WIP for now?

**Comment by pollecuttn** [comment]
Yep :-)

**Pull request closed without merging**
