### PR TITLE
Palette

### PR DESCRIPTION
**Pull request by davidpmccormick**
## What is this PR trying to achieve?

Automating the addition/amending of Cardigan palette colours.

### CODE REVIEW

**Comment by jamesgorrie** [comment]
There is this as well:
https://github.com/Updater/node-sass-json-importer

**Comment by jamesgorrie** [comment]
What're we doing with this @davidpmccormick ?

**Comment by davidpmccormick** [comment]
Just started looking at https://github.com/Updater/node-sass-json-importer this minute.

**Comment by jamesgorrie** [comment]
> Elegant hack

Oxymoron? The rougher the better no?

**Pull request closed without merging**
