### PR TITLE
use title as description on twitter cards if description doesn't exist

### LINKED ISSUE #1420: Twitter cards aren’t showing up if the description field is empty
## Type

- 🐛 Bug

## Needs

- [ ] PM decision: what should be shown as description in sharing cards if the Catalogue API doesn’t include a description?

## Problem to be solved

I [tweeted](https://twitter.com/alexwlchan/status/902977230686617601) a link to https://next.wellcomecollection.org/works/scjvwm7p, but the summary card isn’t showing up:

screen shot 2017-08-30 at 20 33 29

Inspecting the page in question, I see the following suspicious lines of HTML in the `<head>`:

```html
<meta name="twitter:description" content="">
<meta name="description" content="">
```

Inspecting the API result for this page (https://api.wellcomecollection.org/catalogue/v0/works/scjvwm7p), we aren’t including a `description` field, so it’s being left blank. A description is a required field on the “summary with large image” Twitter card, so I guess they’re rejecting the card because it’s empty?

### PR DESCRIPTION
**Pull request by jamesgorrie**
Fixes #1420 

## Type
🐛 Bugfix  

Twitter doesn't consider a card valid without a description.
I'm passing the title in for now, but wonder if something more like, "one of 53,000 image to explore from the Wellcome Collection" <= @jennpb?

screen shot 2017-08-31 at 10 26 52

### CODE REVIEW

**Comment by gestchild** [comment]
Should we put the package updates in a separate PR, so it's clearer they've happened?

**Comment by jamesgorrie** [comment]
> Should we put the package updates in a separate PR, so it's clearer they've happened?

Incremental refactoring...

**Comment by jennpb** [comment]
@jamesgorrie I'm happy to use the title in place of description for now. I'll probably want to revisit this once we start working with other types of content.

**Comment by jamesgorrie** [comment]
Yip - sorry merged it in with that in mind (changing it later).

**Pull request merged**
