### PR TITLE
Node airbag

### PR DESCRIPTION
**Pull request by jamesgorrie**
Adding a node cli interface for airbag.
You will be prompted for the build bucket and number.

This way we remove the chance of human error as we are doing live lookups to AWS / S3.

We could potentially turn this into a lambda, but for now, local is fine. There are going to be more complexities e.g. concurrent / queued deploys, but this is a start.

### CODE REVIEW

**Comment by jamesgorrie** [comment]
@alfraser86 @wellcometrust/wellcomecollection-org

**Comment by jamesgorrie** [comment]
Happy to run through this PR if people would find that easier?

**Comment by davidpmccormick** [comment]
I think I'd benefit from a run-through, aye

**Comment by gestchild** [comment]
yes please

**Comment by jamesgorrie** [comment]
@gestchild @davidpmccormick Happy when you're happy with the code.

**Pull request merged**
