### PR TITLE
update designs on work card

### PR DESCRIPTION
**Pull request by jamesgorrie**
As per #4148 

screenshot 2019-02-21 at 17 50 34

## Next:
Icons

### CODE REVIEW

**Comment by Heesoomoon** [comment]
@jamesgorrie Were you able to follow up about the hover state with @GarethOrmerod? If not, let's follow up on Monday.

**Comment by jamesgorrie** [comment]
> @jamesgorrie Were you able to follow up about the hover state with @GarethOrmerod? If not, let's follow up on Monday.

Good shout, I'll make sure I work with @davidpmccormick too to make sure I reuse the work already done on this.

@davidpmccormick how would I apply the current hover state to this card?

**Comment by davidpmccormick** [comment]
Adding a class of `.card-link` [should do the trick](https://github.com/wellcometrust/wellcomecollection.org/blob/master/common/styles/utilities/_root-scope-classes.scss#L562-L563).

**Comment by jamesgorrie** [comment]
@Heesoomoon following the design and dev of @GarethOrmerod and @davidpmccormick 

screenshot 2019-02-22 at 15 42 54

**Pull request merged**
