### PR TITLE
Remove unused rules

### PR DESCRIPTION
**Pull request by davidpmccormick**
Now that we can import types and modules in the same declaration, we should do so (makes IntelliSense™ work).

@wellcometrust/experience-devs I found that having `"eslint.autoFixOnSave": true` in my IDE settings, and _removing_ `"editor.formatOnSave": true` prevented a bit of weirdness I was seeing.

YMMV.

This change leaves the formatting in the same shape as it was after the mega-lint yesterday, but removes a conflicting error we then had with Standard.

### CODE REVIEW

**Comment by davidpmccormick** [comment]
Following this [eslint-prettier example configuration](https://github.com/prettier/eslint-config-prettier/tree/0f131661f718e278ec1e51529f56450a61f10b11#example-configuration) might actually be the most sensible approach

**Comment by jamesgorrie** [comment]
This has introduced loads of type errors, are we sure we want to continue down this route, or maybe sort those out first in smaller PRs?

**Comment by jamesgorrie** [comment]
e.g. #4064

**Comment by davidpmccormick** [comment]
> This has introduced loads of type errors, are we sure we want to continue down this route, or maybe sort those out first in smaller PRs?

Yeah, this has turned into a nightmare. I'm going to back out for now.

**Comment by jamesgorrie** [comment]
Maybe we have a pause as @wellcometrust/experience-devs and do this together?

**Comment by jamesgorrie** [comment]
Maybe we have a pause as @wellcometrust/experience-devs and do this together?

**Comment by davidpmccormick** [comment]
Closing in favour of #4078

**Pull request closed without merging**
