### PR TITLE
s/relaxed performance/relaxed

### PR DESCRIPTION
**Pull request by jamesgorrie**
Alice made the good point, that they're not all performances, but can be discussions etc - something to bear in mind when remodelling.

### CODE REVIEW

**Comment by jamesgorrie** [comment]
@davidpmccormick it is the work "relaxed" that has meaning, performance was just because we borrowed theatre companies.

**Comment by jamesgorrie** [comment]
@jennpb This was suggested when you were away, but not merged - do you have thoughts on this?

Basically changing `Relaxed performance` => `Relaxed`. 

Question: do they mean the same thing to the communities to which this matters?

Option: We could also have `Relaxed {eventFormat}` e.g. `Relaxed discussion`.

**Comment by jennpb** [comment]
We should keep `Relaxed` as an interpretation, not try to combine it with `{eventFormat}` at this stage. 

We can test with users later, but let's get it merged so it can bed in.

**Comment by jamesgorrie** [comment]
@jennpb this was always implemented as a temporary measure of being on the root of the event (`event.isRelaxed`). 

The reason being is that it didn't feel like an interpretation, but rather a feature of the event. 

Where I thought it made sense in the current model was having it as a policy, but then we need to find a way of surfacing those on the cards.

**Comment by jamesgorrie** [comment]
@jennpb not for the moment.

**Pull request merged**
