### PR TITLE
Add docker config of app

### PR DESCRIPTION
**Pull request by jamesgorrie**
Created a basic docker container.
This will help us move to better deploys and stability.

__Next up__
Add it to a registry, probably [ECR](https://aws.amazon.com/ecr/)

### CODE REVIEW

**Comment by jamesgorrie** [comment]
@alfraser86 for info.

**Comment by alfraser86** [comment]
@jamesgorrie Cool, will be interested to see how you get this integrated with ECS

**Comment by jamesgorrie** [comment]
Yip, next step.

**Comment by alfraser86** [comment]
@jamesgorrie Have you added this to a Docker registry? And if so where. We should definitely have a Wellcome Docker hub.

**Pull request merged**
