### PR TITLE
Added default sizes attribute to articles promos

### PR DESCRIPTION
**Pull request by gestchild**
## What is this PR trying to achieve?

Reduce the page size by providing sizes attribute to images

## What does it look like?

Before:
screen shot 2017-02-17 at 11 49 00
After:
screen shot 2017-02-17 at 11 48 34

### CODE REVIEW

**Comment by jamesgorrie** [comment]
Is it not worth looking at the logic [here](https://github.com/wellcometrust/wellcomecollection.org/blob/master/server/views/components/promo/index.njk#L3-L9) rather - surely 'default' should be in the `else` statement rather than `elif`?

**Comment by gestchild** [comment]
Default refers to one of the 4 weights we have: lead, standalone, default and supporting, rather than a fallback default in the case that nothing is specified.

It is confusing, do you think I should rename the weight type, to something like 'normal'?

**Comment by jamesgorrie** [comment]
I personally prefer default.

I think the misunderstanding is in the idea of the value being optional - which it doesn't feel like it should be.

**Comment by jamesgorrie** [comment]
Or maybe it should be optional - and we remove the `"default"` value?

**Comment by gestchild** [comment]
No, I think you're right it probably shouldn't be optional, I'll amend the logic

**Pull request merged**
