### PR TITLE
Add audio element to article body parts

### LINKED ISSUE #1524: Allow audio players in article body content
## Type
✨  Feature

## UI Requirements
Prismic content creators should be able to upload audio files and have them display within an article.

### PR DESCRIPTION
**Pull request by davidpmccormick**
Closes #1524 

## Type
✨  Feature  

## Value
Displays an (unstyled) html5 audio element to play any audio uploaded to Prismic articles.

## Screenshot
screen shot 2017-09-18 at 16 07 01

### All
- [x] PR labelled and assigned
- [x] Any introduced code complexity has been flagged

### CODE REVIEW

**Comment by davidpmccormick** [comment]
…or we can upload the audio to our SoundCloud account and use the `iframe` component to embed it (which would save us from having to style the audio element)

screen shot 2017-09-18 at 16 10 51

**Comment by pollecuttn** [comment]
@davidpmccormick In the image what's the second blue line with the blue circle? Is it volume? Do you drag the circle to change the volume, or click on the speaker icon?

**Comment by davidpmccormick** [comment]
It's volume, yep. Clicking on the volume icon mutes/unmutes and the slider can be dragged. This is just the browser (Chrome) default styling, though – it'll probably look different elsewhere.

We've got some audio players on this article already: https://wellcomecollection.org/articles/creative-energy

**Comment by davidpmccormick** [comment]
@jamesgorrie maybe we can look at this in the round with [the content model audio stuff](https://github.com/wellcometrust/wellcomecollection-content-model/pull/11#pullrequestreview-63393662) to figure out the best strategy

**Comment by jamesgorrie** [comment]
@pollecuttn That's the standard browser audio player, differs from device to device to be more consistent with the rest of the system e.g. iOS.

**Comment by pollecuttn** [comment]
@davidpmccormick Thanks for the explanation. The volume icon and the volume scrubber seem quite far apart for two related things, but if that's the browser default styling I guess it's familiar to users.

**Comment by davidpmccormick** [comment]
Closing this as the requirement (for _Why Music_) has been better met by SoundCloud embeds in #1621

**Pull request closed without merging**
